import * as store from './storage.js';
import {demoInvoice,uid,today,totals,money,validateInvoice,DESIGNS} from './model.js';
import {layout,svg,generatePDF} from './document.js';
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const titles=['Your Information','Customer','Invoice Details','Services','Design','Preview / PDF'];
const short=['You','Customer','Details','Services','Design','Preview'];
let actionQueue=Promise.resolve();
let invoice,step=0,timer,previewTimer,queue=Promise.resolve(),renderVersion=0,storageOK=true,pdfURL,mode='simple';
function error(e){$('#error').textContent=e.message||String(e);$('#error').hidden=false;}
function clearError(){$('#error').hidden=true;}
function notify(s){$('#notice').textContent=s;$('#notice').hidden=false;}
function field(label,key,value,{type='text',full=false,max=120,optional=false}={}){
 const attrs=`data-field="${key}" maxlength="${max}" autocomplete="off"`;
 const control=type==='textarea'?`<textarea ${attrs} rows="2">${esc(value)}</textarea>`:`<input ${attrs} type="${type}" value="${esc(value)}">`;
 return `<label class="${full?'full':''}">${label}${optional?' <span class="optional">optional</span>':''}${control}</label>`;
}
// Keep typed content out of HTML by escaping every value and attribute.
function personFields(p,prefix){return `<div class="fields">${field(prefix==='sender'?'Business or your name':'Customer name',prefix+'.name',p.name,{full:true})}${field('Attention / office',prefix+'.detail',p.detail,{full:true,optional:true})}${field('Email',prefix+'.email',p.email,{type:'email',optional:true})}${field('Phone',prefix+'.phone',p.phone,{type:'tel',optional:true})}${field('Address',prefix+'.address',p.address,{type:'textarea',full:true,max:400,optional:true})}</div>`;}
function totalHTML(){try{const t=totals(invoice);return `<div><span>Subtotal</span><span>${money(t.subtotal)}</span></div><div><span>Discount</span><span>−${money(t.discount)}</span></div><div><span>Tax</span><span>${money(t.tax)}</span></div><div><span>Total due</span><span>${money(t.total)}</span></div>`;}catch(e){return `<p>${esc(e.message)}</p>`;}}
function servicesHTML(){return invoice.items.map((x,i)=>`<section class="service" data-service="${i}"><div class="service-top"><b>SERVICE ${String(i+1).padStart(2,'0')}</b><button type="button" data-action="remove-service" data-index="${i}" ${invoice.items.length===1?'disabled':''}>Remove</button></div><div class="fields service-fields">${field('Date',`items.${i}.date`,x.date,{type:'date'})}${field(mode==='advanced'?'Rate ($)':'Amount ($)',`items.${i}.rate`,x.rate)}${mode==='advanced'?field('Quantity',`items.${i}.quantity`,x.quantity):''}${field('Description',`items.${i}.description`,x.description,{type:'textarea',max:6000,full:true})}</div><strong class="line-total" data-line-total="${i}"></strong></section>`).join('')+`<button type="button" data-action="add-service">＋ Add service</button>${mode==='advanced'?`<details open><summary>Tax & discount</summary><p class="helper">Discount is applied before tax.</p><div class="fields">${field('Tax (%)','tax',invoice.tax)}<label>Discount type<select data-field="discountType"><option value="amount" ${invoice.discountType==='amount'?'selected':''}>Amount ($)</option><option value="percent" ${invoice.discountType==='percent'?'selected':''}>Percent (%)</option></select></label>${field('Discount','discount',invoice.discount)}</div></details>`:''}<div class="totals ${mode==='simple'?'simple-total':''}">${totalHTML()}</div>`;}
function resizeTextareas(){document.querySelectorAll('textarea').forEach(t=>{t.style.height='auto';t.style.height=Math.max(72,t.scrollHeight+2)+'px';});}
function updateTotals(){const t=$('.totals');if(t)t.innerHTML=totalHTML();try{const values=totals(invoice);document.querySelectorAll('[data-line-total]').forEach(e=>e.textContent=money(values.rows[Number(e.dataset.lineTotal)]));}catch{document.querySelectorAll('[data-line-total]').forEach(e=>e.textContent='—');}}
async function render(){
 $('#demo-banner').hidden=!invoice.demo;
 $('#steps').innerHTML=titles.map((t,i)=>`<button type="button" data-action="step" data-step="${i}" aria-label="${i+1}. ${t}" ${i===step?'aria-current="step"':''} class="${i<step?'done':''}"><b>${i+1}</b>${short[i]}</button>`).join('');
 const intros=['The name behind the good work.','Who are you billing?','A few details to keep things in order.','Add your work. We’ll handle the arithmetic.','Three considered designs. One great first impression.','Ready for your customer. Review, save and download.'];
 let body='';
 if(step===0)body=personFields(invoice.sender,'sender');
 if(step===1){const customers=await store.all('customers').catch(()=>[]);body=`<label class="reuse">Reuse a customer<select id="reuse-customer"><option value="">Choose a saved customer…</option>${customers.map((p,i)=>`<option value="${i}">${esc(p.name)}${p.detail?' — '+esc(p.detail):''}</option>`).join('')}</select></label>`+personFields(invoice.customer,'customer');$('#step-content')._customers=customers;}
 if(step===2)body=`<div class="fields">${field('Invoice number','number',invoice.number,{max:60})}${field('Invoice date','date',invoice.date,{type:'date'})}${mode==='advanced'?field('Payment terms','due',invoice.due,{full:true})+field('PO / reference','reference',invoice.reference,{full:true,optional:true}):''}${field('Message','message',invoice.message,{type:'textarea',full:true,max:2000,optional:true})}${mode==='advanced'?field('Payment instructions','payment',invoice.payment,{type:'textarea',full:true,max:2000,optional:true}):''}</div>`;
 if(step===3)body=servicesHTML();
 if(step===4)body=`<div class="design-grid">${DESIGNS.map((d,i)=>`<button type="button" class="design-card" data-action="design" data-design="${d}" aria-pressed="${d===invoice.design}"><span id="mini-${d}"></span><strong>${d[0].toUpperCase()+d.slice(1)}</strong><small>${['Traditional & crisp','Modern & confident','Quiet & editorial'][i]}</small></button>`).join('')}</div><p class="design-help">Tap a full-size example to choose it. The PDF uses this exact layout.</p>`;
 if(step===5)body=`<div class="preview-actions"><button type="button" class="primary" data-action="pdf">Download PDF ↓</button><button type="button" data-action="save">Save invoice</button></div><div id="pdf-result"></div><p class="helper">US Letter · Selectable text · No watermark</p><div id="main-preview" class="paper-stack mobile-preview"></div><div class="totals">${totalHTML()}</div>`;
 $('#step-content').innerHTML=`<h2 tabindex="-1">${titles[step]}</h2><p class="step-intro">${intros[step]}</p>`+body;
 $('#back').disabled=step===0;$('#next').hidden=step===5;$('#step-label').textContent=`${step+1} of 6`;$('#next').textContent=step===4?'Preview →':'Next →';
 resizeTextareas();updateTotals();schedulePreview(0);await updateCount();
}
async function updateCount(){$('#saved-count').textContent=(await store.all('invoices').catch(()=>[])).length;}
function scheduleSave(){clearTimeout(timer);$('#save-status').textContent='Saving…';timer=setTimeout(()=>flush().catch(error),300);}
async function flush(){clearTimeout(timer);const snapshot=structuredClone(invoice);const at=step;snapshot.updatedAt=new Date().toISOString();queue=queue.catch(()=>{}).then(()=>store.saveDraft(snapshot,at));try{await queue;storageOK=true;$('#save-status').textContent='Saved on this device';}catch(e){storageOK=false;$('#save-status').textContent='Not saved — export a backup';throw new Error('Browser storage is unavailable or full. Your edits are still on screen. Export a backup before closing this tab.');}}
function schedulePreview(delay=350){clearTimeout(previewTimer);previewTimer=setTimeout(()=>renderPreviews().catch(error),delay);}
async function renderPreviews(){const version=++renderVersion;const data=structuredClone(invoice);try{const doc=await layout(data);if(version!==renderVersion)return;$('#side-preview').innerHTML=doc.pages.map(svg).join('');$('#design-name').textContent=invoice.design.toUpperCase();if($('#main-preview'))$('#main-preview').innerHTML=doc.pages.map(svg).join('');if(step===4){for(const d of DESIGNS){const m=await layout(data,d);if(version!==renderVersion)return;const target=$('#mini-'+d);if(target)target.innerHTML=svg(m.pages[0]);}}}catch(e){if(version!==renderVersion)return;$('#side-preview').textContent='Complete the invoice fields to refresh your preview.';if($('#main-preview'))$('#main-preview').textContent='Complete the invoice fields to refresh your preview.';if(step===4||step===5)error(e);}}
function setPath(path,value){const parts=path.split('.');const key=parts.pop();parts.reduce((o,k)=>o[k],invoice)[key]=value;}
function download(blob,name){const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);return url;}
function openModal(title,body){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;if(!$('#modal').open)$('#modal').showModal();}
async function library(){await flush();const invoices=await store.all('invoices');invoices.sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt));openModal('Saved invoices',invoices.length?invoices.map(d=>`<div class="library-row"><div><strong>${esc(d.number)}${d.demo?' · Example':''}</strong><small>${esc(d.customer.name)} · ${money(totals(d).total)}</small></div><div class="library-actions"><button type="button" data-action="open" data-id="${esc(d.id)}">Open</button><button type="button" data-action="duplicate" data-id="${esc(d.id)}">Duplicate</button><button type="button" class="danger" data-action="delete" data-id="${esc(d.id)}">Delete</button></div></div>`).join(''):'<p>No saved invoices yet. Use “Save invoice” in Preview / PDF to keep a finished invoice here. Your current draft autosaves separately.</p>');}
async function settings(){let persisted=false;if(navigator.storage?.persisted)persisted=await navigator.storage.persisted();openModal('Your data, your device',`<p>Invoice data is stored only in this browser using IndexedDB. It is not uploaded to us.</p><p>Clearing site data or using another device or browser can remove access to your invoices. Private browsing may erase data when the session ends. Keep regular backups.</p><p id="persistent-status" class="helper">${persisted?'Persistent storage is enabled.':'Persistent storage is not enabled. Your browser decides whether to grant it.'}</p><div class="modal-actions"><button type="button" data-action="persist">Protect local storage</button><button type="button" class="primary" data-action="backup">Export Backup</button><button type="button" data-action="restore">Restore Backup</button></div><p class="helper">Backups include your contacts, saved invoices, active draft, numbering and design preferences. Store them somewhere private. Restore replaces this tool’s local data after confirmation.</p><button type="button" data-action="example">Load fictional example</button>`);}
async function navigate(n){await flush();step=Math.max(0,Math.min(5,n));await render();await flush();$('#step-content h2').focus({preventScroll:true});$('#steps').scrollIntoView({block:'start',behavior:'instant'});}
async function runAction(action,target){
 clearError();
 if(action==='close')return $('#modal').close();
 if(action==='mode'){mode=target.dataset.mode;document.querySelectorAll('[data-action="mode"]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));return render();}
 if(action==='next')return navigate(step+1);if(action==='back')return navigate(step-1);if(action==='step')return navigate(Number(target.dataset.step));
 if(action==='new'||action==='example'){
  if(!invoice.demo&&!confirm('Start a new draft? Save the current invoice first if you want to keep it in Saved invoices.'))return;
  if(action==='new'&&navigator.storage?.persist)navigator.storage.persist().catch(()=>{});
  await flush();invoice=action==='example'?demoInvoice():await store.createInvoice();step=0;$('#modal').close();await flush();return render();
 }
 if(action==='add-service'){if(invoice.items.length>=200)throw new Error('An invoice supports up to 200 services.');invoice.items.push({id:uid(),date:today(),description:'',quantity:'1',rate:'0.00'});await render();scheduleSave();const fields=document.querySelectorAll('[data-field$=".description"]');fields[fields.length-1].focus();return;}
 if(action==='remove-service'){if(invoice.items.length>1){invoice.items.splice(Number(target.dataset.index),1);await render();scheduleSave();}return;}
 if(action==='design'){invoice.design=target.dataset.design;await render();scheduleSave();return;}
 if(action==='library')return library();if(action==='settings')return settings();
 if(action==='save'){validateInvoice(invoice,true);await flush();await store.saveInvoice(invoice);await updateCount();notify('Invoice saved. Find it in Saved invoices.');return;}
 if(action==='pdf'){
  validateInvoice(invoice,true);target.disabled=true;target.textContent='Preparing PDF…';
  try{const {blob}=await generatePDF(invoice);if(pdfURL)URL.revokeObjectURL(pdfURL);pdfURL=URL.createObjectURL(blob);const name=invoice.number.replace(/[^a-z0-9_-]/gi,'_')||'invoice';download(blob,name+'.pdf');$('#pdf-result').innerHTML=`<a class="pdf-link" href="${pdfURL}" target="_blank" rel="noopener">Open PDF ↗</a><p class="helper">On iPhone, open the PDF and use Share → Save to Files.</p>`;}finally{target.disabled=false;target.textContent='Download PDF ↓';}return;
 }
 if(action==='open'||action==='duplicate'){await flush();const d=await store.get('invoices',target.dataset.id);if(!d)throw new Error('This invoice was removed in another tab.');if(action==='duplicate'){const fresh=await store.createInvoice();invoice={...d,id:fresh.id,number:fresh.number,date:today(),demo:d.demo,updatedAt:new Date().toISOString()};}else invoice=d;step=0;$('#modal').close();await flush();return render();}
 if(action==='delete'){if(!confirm('Delete this saved invoice from this browser? This cannot be undone without a backup.'))return;const active=invoice.id===target.dataset.id;await store.removeInvoice(target.dataset.id);if(active){invoice=await store.createInvoice();step=0;await flush();await render();}await updateCount();return library();}
 if(action==='persist'){const ok=navigator.storage?.persist?await navigator.storage.persist():false;$('#persistent-status').textContent=ok?'Persistent storage is enabled. Keep backups too.':'Your browser did not grant persistent storage. Keep regular backups.';return;}
 if(action==='backup'){try{await flush();}catch{/* Export current in-memory draft even when writes fail. */}let b;try{b=await store.snapshot();}catch{b={format:'ds-digital-invoices',version:1,createdAt:new Date().toISOString(),stores:{profiles:[],customers:[],invoices:[],drafts:[],preferences:[],numbering:[]}};}b.stores.drafts=[['active',structuredClone(invoice)]];b.stores.preferences=[['ui',{design:invoice.design,step}]];download(new Blob([JSON.stringify(b,null,2)],{type:'application/json'}),`invoice-backup-${today()}.json`);notify(storageOK?'Backup exported. Keep it in a safe place.':'Recovery backup exported with your current draft. Stored records may be unavailable.');return;}
 if(action==='restore'){$('#restore-file').click();return;}
}
document.addEventListener('input',e=>{const t=e.target;if(!t.dataset.field)return;clearError();setPath(t.dataset.field,t.value);resizeTextareas();updateTotals();scheduleSave();schedulePreview();});
document.addEventListener('change',async e=>{if(e.target.id==='reuse-customer'&&e.target.value!==''){invoice.customer=structuredClone($('#step-content')._customers[Number(e.target.value)]);await render();scheduleSave();}if(e.target.dataset.field){setPath(e.target.dataset.field,e.target.value);scheduleSave();schedulePreview();}});
document.addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(!target||!invoice)return;const action=target.dataset.action;actionQueue=actionQueue.then(async()=>{$('#workspace').setAttribute('aria-busy','true');try{await runAction(action,target);}catch(err){error(err);}finally{$('#workspace').setAttribute('aria-busy','false');}});});
$('#restore-file').addEventListener('change',async e=>{const f=e.target.files[0];e.target.value='';if(!f)return;try{if(f.size>20*1024*1024)throw new Error('Backups must be smaller than 20 MB.');const b=store.validateBackup(JSON.parse(await f.text()));if(!confirm('Replace all Invoice Maker data in this browser with this backup? Export a backup of current data first.'))return;clearTimeout(timer);await queue.catch(()=>{});await store.restore(b);({invoice,step}=await store.load());$('#modal').close();await render();notify('Backup restored. Your invoices and preferences are ready.');}catch(err){error(new Error('Restore failed. '+err.message));}});
document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='hidden'&&invoice)flush().catch(()=>{});});
window.addEventListener('beforeunload',e=>{if($('#save-status').textContent==='Saving…'||!storageOK){e.preventDefault();e.returnValue='';}});
// Boot directly for broad mobile-browser compatibility. IndexedDB transactions already protect individual writes.
async function boot(){try{({invoice,step}=await store.load());await render();await flush();}catch(e){invoice ||= demoInvoice();await render();storageOK=false;$('#save-status').textContent='Storage unavailable';error(e);}}
boot();
